Translate to ptBR the setup section of the basic training
nextflow-io/training pull request #164
Opened 2023-02-15 19:20 UTC by mribeirodantas

Signed-off-by: Marcel Ribeiro-Dantas <mribeirodantas@seqera.io>

2023-02-15 19:39 UTC, mribeirodantas commented
I'm a bit unsure of how to translate (or if we should translate it at all) _quick start_ into Portuguese.

2023-02-16 19:33 UTC, jvfe requested changes
Just a few nitpicks but the translation looks good!

2023-02-16 19:33 UTC, jvfe commented on docs/basic_training/setup.pt.md
> +Existem duas maneiras principais de começar este treinamento em Nextflow da Seqera.
```suggestion
Existem duas principais maneiras de começar este treinamento em Nextflow da Seqera.
```

2023-02-16 19:33 UTC, jvfe commented on docs/basic_training/setup.pt.md
> +A segunda é usar o [Gitpod](#gitpod), o que é melhor para iniciantes, pois esta plataforma contém todos os programas e dados necessários. Basta clicar no link e fazer login usando sua conta do GitHub
```suggestion
A segunda é usar o [Gitpod](#gitpod), o que é melhor para iniciantes, pois esta plataforma contém todos os programas e dados necessários. Basta clicar no link abaixo e fazer login usando sua conta do GitHub para iniciar o tutorial:
```

2023-02-16 19:33 UTC, jvfe commented on docs/basic_training/setup.pt.md
> +Verifique a instalação correta do `nextflow` executando o seguinte comando:
```suggestion
Verifique se o `nextflow` instalou corretamente executando o seguinte comando:
```

2023-02-16 19:33 UTC, jvfe commented on docs/basic_training/setup.pt.md
> +Um ambiente de desenvolvimento Nextflow pré-configurado está disponível usando o Gitpod.
```suggestion
Um ambiente de desenvolvimento Nextflow pré-configurado está disponível no Gitpod.
```

2023-02-16 19:33 UTC, jvfe commented on docs/basic_training/setup.pt.md
> +-   **A janela principal** permite visualizar e editar arquivos. Clicar em um arquivo no explorer o abrirá na janela principal. Você também deve ver o material de treinamento em uma janela (<https://
```suggestion
-   **A janela principal** permite visualizar e editar arquivos. Clique em um arquivo no explorer para abri-lo na janela principal. Você também pode ver o material de treinamento em uma das janelas (<https://training.nextflow.io/>).
```

2023-02-16 19:33 UTC, jvfe commented on docs/basic_training/setup.pt.md
> +Para testar se o ambiente está funcionando corretamente, digite o seguinte no terminal:
```suggestion
Para testar se o ambiente está funcionando corretamente, digite o seguinte comando no terminal:
```

2023-02-16 19:34 UTC, jvfe commented
> I'm a bit unsure of how to translate (or if we should translate it at all) _quick start_ into Portuguese.

I vote for leaving it as is since translated it would probably sound weird.

2023-02-16 23:25 UTC, mribeirodantas commented
Thanks, @jvfe ! 🥳

2023-02-16 23:29 UTC, jvfe approved these changes

2023-02-17 00:08 UTC, merged