Translate to Brazilian Portuguese the modules section of the basic training
nextflow-io/training pull request #196
Opened 2023-03-03 01:21 UTC by iaradsouza1

## Description

This is a first version for modules translation.

2023-03-03 02:14 UTC, mribeirodantas requested changes

2023-03-03 02:14 UTC, mribeirodantas commented on docs/basic_training/modules.pt.md
> +    Você pode encontrar exemplos disso em repositórios públicos, como o [tutorial Seqera RNA-Seq](https://github.com/seqeralabs/rnaseq-nf/tree/master/modules) ou em pipelines do nf-core, como [nf-cor
```suggestion
    Você pode encontrar exemplos disso em repositórios públicos, como no [tutorial de RNA-Seq da Seqera](https://github.com/seqeralabs/rnaseq-nf/tree/master/modules) ou em pipelines do nf-core, como o [nf-core/rnaseq](https://github.com/nf-core/rnaseq/tree/master/modules/nf-core/modules).
```

2023-03-03 02:14 UTC, mribeirodantas commented on docs/basic_training/modules.pt.md
> +O resultado do snippet acima pode ser acessado usando `my_pipeline.out.my_data`.
```suggestion
O resultado do trecho de código acima pode ser acessado usando `my_pipeline.out.my_data`.
```

2023-03-03 02:14 UTC, mribeirodantas commented on docs/basic_training/modules.pt.md
> +Para visualizar um resumo das alterações introduzidas quando o Nextflow migrou de DSL1 para DSL2, consulte as [notas de migração DSL2](https://www.nextflow.io/docs/latest/dsl2.html#dsl2-migration-not
```suggestion
Para visualizar um resumo das alterações introduzidas quando o Nextflow migrou da DSL1 para a DSL2, consulte as [notas de migração da DSL2](https://www.nextflow.io/docs/latest/dsl2.html#dsl2-migration-notes) na documentação oficial do Nextflow.
```

2023-03-04 18:27 UTC, iaradsouza1 reviewed
Thanks for reviewing, @mribeirodantas ! I think it's ok now.

2023-03-04 21:02 UTC, mribeirodantas approved these changes

2023-03-04 21:06 UTC, merged