Improve foundational
nextflow-io/training pull request #298
Opened 2024-01-15 12:49 UTC by christopher-hakkaart

- Fix code blocks

2024-01-15 16:23 UTC, mribeirodantas requested changes

2024-01-15 16:57 UTC, mribeirodantas approved these changes

2024-01-15 16:57 UTC, mribeirodantas commented
Hey, @christopher-hakkaart. Feel free to revert any commit you think may go against the standardization you had in mind. If you're happy with it, LGTM! 😉

2024-01-16 11:14 UTC, christopher-hakkaart commented
Looks good! Thanks again!

2024-01-16 11:14 UTC, merged