Simplify hello-gatk
nextflow-io/training pull request #364
Opened 2024-09-03 17:52 UTC by adamrtalbot

This PR simplifies the hello-gatk example.

- Uses simpler data inputs which are much, much smaller enhancing portability
- Reduces reliance on samplesheets to make handling inputs more approachable for a beginner
- Uses only 1 operator (`collect`), which makes it more obvious what each step does

Negatives:
 - doesn't include any 'interesting' operators, which might show how to use channels
 - uses a weird chromosome (`chr20:coordinateStart-coordinateEnd`) which is harder to develop for us

2024-09-04 00:52 UTC, mribeirodantas commented on docs/hello_nextflow/04_hello_modules.md
> + * Call variants with GATK HapolotypeCaller in GVCF mode
```suggestion
 * Call variants with GATK HaplotypeCaller in GVCF mode
```

2024-09-04 00:54 UTC, mribeirodantas commented on hello-nextflow/hello-modules.nf
> + * Call variants with GATK HapolotypeCaller in GVCF mode
```suggestion
 * Call variants with GATK HaplotypeCaller in GVCF mode
```

2024-09-04 00:57 UTC, mribeirodantas requested changes
From a quick look, it seems cool! It'd be good if someone else could try out the new version of this training.

2024-09-06 22:00 UTC, vdauwera commented
Reviewing the overall flow right now, at first and second glance everything looks really good, I like that this is simpler. We can always demonstrate more advanced stuff in later trainings.

One quick comment is I noticed the new use of `checkIfExists: true` but it's not formally explained/introduced anywhere in the text, would be nice to put in a short explanation (and link to docs which we should do more anyway)

Also I noticed this numbering/header issue:

<img width="748" alt="Screenshot 2024-09-06 at 5 59 11 PM" src="https://github.com/user-attachments/assets/2347a438-fed1-4dec-a236-2be6391792fe">

2024-09-24 19:03 UTC, kenibrewer commented
@adamrtalbot Just a heads up that we'd like to merge this for our training in SF tomorrow.

2024-09-25 07:33 UTC, vdauwera commented
> > @adamrtalbot Just a heads up that we'd like to merge this for our training in SF tomorrow.
> 
> I'm happy with it, if you are hit merge.
> 
> Currently needs an approval 😉

I've reviewed in more detail and I feel like there's a couple of things that are a bit of a jump, so I'm making an intermediate version with most but not all of the changes

2024-10-04 19:23 UTC, vdauwera commented
Most of the changes in here were made in my recent PR (thanks @adamrtalbot for your hard work!) so this is no longer going to be used, but I'm leaving it open for now in case there's anything else we want to pilfer from it.

2024-10-25 00:54 UTC, kenibrewer commented
Going to close this now that we've done the re-design of hello-gatk in dev.

2024-10-25 00:54 UTC, closed without merging