New multi-course structure for training materials
nextflow-io/training pull request #486
Opened 2024-12-16 22:58 UTC by vdauwera

First step toward evolving Hello Nextflow to be more modular. Just content moves and stub creation (not updated content yet except some rough chopping where bits are getting split up).

2025-01-15 09:20 UTC, pinin4fjords commented on docs/hello_nextflow/01_hello_world.md
> +This is preferable when you're dealing with very large files.
```suggestion
This is preferable when you're dealing with very large files you don't need to retain longer term.
```

I still maintain that the practical applications of the default symliking are few.

2025-01-15 10:24 UTC, pinin4fjords commented on docs/hello_nextflow/02_hello_channels.md
> +However... This seems to indicate that '3 of 3' calls were made for the process, which is encouraging, but this only give us one subdirectory path. What's going on?
```suggestion
However... This seems to indicate that '3 of 3' calls were made for the process, which is encouraging, but this only shows us a single run of the process, with one subdirectory path (`3d/1fe62c...`). What's going on?
```

The previous one made me think I should be looking at the actual directories momentarily.

2025-01-15 10:24 UTC, pinin4fjords commented on docs/hello_nextflow/02_hello_channels.md
> +This time we see all six work subdirectories listed in the output:
```suggestion
This time we see all three process runs and their associated work subdirectories listed in the output:
```

2025-01-15 10:24 UTC, pinin4fjords commented on docs/hello_nextflow/02_hello_channels.md
> +For a complex workflow, or a large number of inputs, having the full list output to the terminal might get a bit overwhelming.
```suggestion
For a complex workflow, or a large number of inputs, having the full list output to the terminal might get a bit overwhelming, so you might not choose to use `-ansi-log false` in those cases.
```

2025-01-15 10:24 UTC, pinin4fjords commented on docs/hello_nextflow/02_hello_channels.md
> +You can check the contents of `output.txt`; you will find only one of the three.
Add an example cat command?

2025-01-15 10:24 UTC, pinin4fjords commented on docs/hello_nextflow/02_hello_channels.md
> +So how do we make the file names unique? A common way to do that is to use some unique piece of metadata as part of the file name.
```suggestion
So how do we make the file names unique? A common way to do that is to use some unique piece of metadata from the inputs (received from the input channel) as part of the output file name.
```

2025-01-15 10:24 UTC, pinin4fjords commented on docs/hello_nextflow/02_hello_channels.md
> +This should produce a unique output file name every time the process is called.
```suggestion
This should produce a unique output file name every time the process is called, so that it can be distinguished from the outputs from other iterations of the same process in the output directory.
```
Just doubling down, not sure if it's helpful.

2025-01-15 10:24 UTC, pinin4fjords commented on docs/hello_nextflow/02_hello_channels.md
> +    You'll learn how to do that later in your Nextflow training.
```suggestion
    In practice, naming files based on the input data itself is almost always impractical.
    The better way to generate dynamic filenames is to pass metatdata to a process along with the input files. We can derive that metadata from a sample sheet as we're reading the input files. 
    You'll learn how to do that later in your Nextflow training.
```

I think the current note is too complex for someone just getting used to the idea of channels.

2025-01-15 10:24 UTC, pinin4fjords commented on docs/hello_nextflow/02_hello_channels.md
> +You know how to feed a batch of multiple input elements through a channel.
```suggestion
You know how to feed multiple input elements through a channel.
```

2025-01-15 10:24 UTC, pinin4fjords commented on docs/hello_nextflow/02_hello_channels.md
> +We want to be able to specify the input from the command line, since that is the piece that will almost always be different in subsequent runs of the workflow.
```suggestion
When we're actually using our workflow, we want to be able to control its inputs from the command line. 
```

2025-01-15 10:24 UTC, pinin4fjords commented on docs/hello_nextflow/02_hello_channels.md
> +## 4. Supply a batch of multiple values via the `params` system
Would this not be a good place to stop, and have a subsequent (possibly quite short) 'hello operators', using `flatten` and `splitCsv` as exemplars?

2025-01-15 10:51 UTC, pinin4fjords commented on docs/hello_nextflow/03_hello_plumbing.md
> +3. Passing more than one input through a channel
We just did that in the previous module, right?

2025-01-15 10:51 UTC, pinin4fjords commented on docs/hello_nextflow/03_hello_plumbing.md
> +# Part 3: Hello Plumbing
```suggestion
# Part 3: Hello Workflows
```
Maybe? We haven't really had a workflow so far, just a single step- this marks the point where we actually move beyond a single process into genuine worflows.

2025-01-15 10:51 UTC, pinin4fjords commented on docs/hello_nextflow/03_hello_plumbing.md
> +This time, we're going to make the following changes to our workflow:
```suggestion
This time, we're going to make the following changes to our workflow to better reflect how people build actual workflows:
```

2025-01-15 10:51 UTC, pinin4fjords commented on docs/hello_nextflow/03_hello_plumbing.md
> +3. Add a parameter to name the final output file and pass that as a secondary input to the collection step;
```suggestion
1. Add a second step that converts the greeting to uppercase.
2. Add a third step that collects all the transformed greetings and writes them into a single file.
3. Add a parameter to name the final output file and pass that as a secondary input to the collection step.
```

2025-01-15 10:51 UTC, pinin4fjords commented on docs/hello_nextflow/03_hello_plumbing.md
> +We want to add a second step to convert the greeting to uppercase, using the classic UNIX text replacement command `tr '[a-z]' '[A-Z]'`.
```suggestion
Real workflows have more than one process! So it's time to start adding some more.

We'll add a second step to convert the greeting to uppercase, using the classic UNIX text replacement command `tr '[a-z]' '[A-Z]'`.
```

2025-01-15 10:51 UTC, pinin4fjords commented on docs/hello_nextflow/03_hello_plumbing.md
> +The step we want to add to our workflow will use the text replacement command `tr '[a-z]' '[A-Z]'` to convert the greetings output by the first step to uppercase.
```suggestion
The step we want to add to our workflow will use the text replacement command `tr '[a-z]' '[A-Z]'` to convert the greetings output by the first step to uppercase.
```
Repetitive with above.

2025-01-15 10:51 UTC, pinin4fjords commented on docs/hello_nextflow/03_hello_plumbing.md
> +
```suggestion
(you'll need to adapt this tree command to the actual directory name you see in the output from your workflow run)

```

2025-01-15 10:51 UTC, pinin4fjords commented on docs/hello_nextflow/03_hello_plumbing.md
> +By default, Nextflow uses symbolic links rather than copies to stage input and intermediate files.
```suggestion
By default, when running on a single machine as we're doing here, Nextflow uses symbolic links rather than copies to stage input and intermediate files.
```

Gets more complex when we start talking about cloud etc.

2025-01-15 10:51 UTC, pinin4fjords commented on docs/hello_nextflow/03_hello_plumbing.md
> +When we apply a transformation to a batch of inputs, like we're doing here to the multiple greetings, we'll often want to collect the transformed outputs and feed them into a single step that perform
```suggestion
When we use a process to apply a transformation to each of the elements in a channel, like we're doing here to the multiple greetings, we sometimes want to collect elements from the output channel of that process, and feed them into another process that performs some kind of analysis or summation.
```

I think it's worth being specific with the channel/ process language, since we've introduced those concepts, so that people get used to them.

2025-01-15 10:51 UTC, pinin4fjords commented on docs/hello_nextflow/03_hello_plumbing.md
> +Here we're simply going to write them all out to a single file, using the UNIX `cat` command.
```suggestion
In the next step we're simply going to write all the elements of a channel to a single file, using the UNIX `cat` command.
```

2025-01-15 10:51 UTC, pinin4fjords commented on docs/hello_nextflow/03_hello_plumbing.md
> +This is what we can write based on what you've learned so far.
Is this really true? We already know about variable path inputs, and the syntax isn't different for multiple files.

2025-01-15 10:51 UTC, pinin4fjords commented on docs/hello_nextflow/03_hello_plumbing.md
> +You know how to pass more than one input through a channel.
```suggestion
You know how to pass collected inputs through a channel.
```

To dissambuguate from the earlier examples with multiple items.

2025-01-15 13:36 UTC, vdauwera commented on docs/hello_nextflow/02_hello_channels.md
> +    You'll learn how to do that later in your Nextflow training.
completely agree

2025-01-15 13:39 UTC, vdauwera commented on docs/hello_nextflow/03_hello_plumbing.md
> +3. Passing more than one input through a channel
Do you mean "Passing more than one input through a channel"? Here it's about having multiple 'tracks' in the input channel, eg the data but also some parameters etc., as a opposed to 'several pieces of the same kind of data'. In general this is a point of confusion for which we should try to develop a controlled vocabulary, because 'multiple inputs' ends up being ambiguous

2025-01-15 13:42 UTC, vdauwera commented on docs/hello_nextflow/03_hello_plumbing.md
> +# Part 3: Hello Plumbing
I'm totally open to changing the name. FWIW 'Plumbing' speaks to me because it feels directly evocative of what this one is about, ie specifically how do you connect the pipes. I worry that 'Workflows' is maybe a bit too generic; I see what you're going for but is that going to be obvious to a naive user? They might go "isn't it all about workflows?" Perhaps we can poll for opinions/suggestions.

2025-01-15 13:46 UTC, vdauwera commented on docs/hello_nextflow/03_hello_plumbing.md
> +This is what we can write based on what you've learned so far.
Well we don't know yet that the syntax isn't different. As a naive user, I'm like ok, I'm confident in all of this, but for this next bit I need to check if the syntax is the same or if i need to do something special.

2025-01-15 13:49 UTC, vdauwera commented on docs/hello_nextflow/03_hello_plumbing.md
> +You know how to pass more than one input through a channel.
I find this _more_ ambiguous though; this reads like it's about the collected greetings, but it's not; it's about that parameter that constitutes an extra 'track' in the input channel. This is exactly what I was talking about in my other comment just now; the ways we talk about multiple inputs is inconsistent and confusing.

2025-01-15 14:18 UTC, pinin4fjords commented on docs/hello_nextflow/03_hello_plumbing.md
> +3. Passing more than one input through a channel
Yes, I actually realised what you meant further down. This probably needs to be something like 'passing collections of elements to a single task' or something similar.

2025-01-15 14:20 UTC, pinin4fjords commented on docs/hello_nextflow/03_hello_plumbing.md
> +# Part 3: Hello Plumbing
This was kind of conscious (kind of). I was thinking the first sentence could be along the lines "You thought you'd been thinking about workflows already, but real workflows do these things..."

2025-01-15 14:22 UTC, pinin4fjords commented on docs/hello_nextflow/03_hello_plumbing.md
> +You know how to pass more than one input through a channel.
To me 'passing more than one input through a channel' covers both things- you're doing it in both cases. The difference here is that we're passing multiple inputs to a single task (a task being a single iteration of a process).

2025-01-15 14:50 UTC, vdauwera commented on docs/hello_nextflow/03_hello_plumbing.md
> +You know how to pass more than one input through a channel.
But that's not what this specific line is about; that's not the takeaway. The takeaway from this specific section is that we now know that if the process expects `path foo` and `val bar`, i have to write the process call as `myProcess(foo, bar)`. Before this, all I knew to do was `myProcess(foo)`.

2025-01-15 15:01 UTC, vdauwera commented on docs/hello_nextflow/02_hello_channels.md
> +## 4. Supply a batch of multiple values via the `params` system
As discussed in slack, I'll add some more explicit text calling out the importance of operators in section 4 and won't split anything out for now.

2025-01-15 15:04 UTC, vdauwera commented on docs/hello_nextflow/03_hello_plumbing.md
> +3. Passing more than one input through a channel
Are you using 'collections of elements' in the same way I'm using 'input tracks in a channel'?

2025-01-15 17:39 UTC, pinin4fjords commented on docs/hello_nextflow/03_hello_plumbing.md
> +You know how to pass more than one input through a channel.
OK, apologies for the quick comment, I conflated issues while multitasking and I've re-read. 

In fact, the point of this section (section 3) is that we've added a second input to the process, and filled that from a new parameter, right? So both of our versions are wrong. It's nothing to do with multiple inputs through 'a' channel (in fact there are now 2 channels, though one is implicit).

Maybe something like:

```
You know how to add more than one input channel to a process, and use both inputs from the workflow
```

2025-02-13 22:39 UTC, vdauwera commented on docs/hello_nextflow/03_hello_plumbing.md
> +You know how to pass more than one input through a channel.
Updated this in a previous pass, thanks for clarifying

2025-02-13 22:40 UTC, vdauwera commented on docs/hello_nextflow/03_hello_plumbing.md
> +# Part 3: Hello Plumbing
This was changed to Hello Workflow based on group consensus

2025-02-13 22:40 UTC, vdauwera commented on docs/hello_nextflow/03_hello_plumbing.md
> +3. Passing more than one input through a channel
fixed this in a previous pass

2025-02-14 06:38 UTC, vdauwera commented
First green check in two months, thank you @kenibrewer for fixing the pre-commit stuff 🥹

2025-02-15 04:20 UTC, mribeirodantas commented on docs/hello_nextflow/01_hello_world.md
> +### 1.2 The `process` definition
```suggestion
### 1.2 The `process` block
```

2025-02-15 04:24 UTC, mribeirodantas commented on docs/hello_nextflow/01_hello_world.md
> +    This is necessary for verifying that the command was executed successfully and for passing the output to downstream processes if needed.
```suggestion
    This is necessary for verifying that the command was executed successfully and for passing the output to downstream processes if needed. Output produced that doesn't match what is declared in the output block will not be passed to downstream processes.
```

2025-02-15 04:29 UTC, mribeirodantas commented on docs/hello_nextflow/01_hello_world.md
> +In a real-world pipeline, a process usually contains additional blocks such as directives, inputs, and conditional clauses, which we'll introduce later in this training course.
Will we? I did a quick search and couldn't find examples of conditional clauses in this training course.

2025-02-15 04:37 UTC, mribeirodantas commented on docs/hello_nextflow/01_hello_world.md
> +- **`.command.sh`**: The command that was run by the process call call
```suggestion
- **`.command.sh`**: The command that was actually run by the process call
```

2025-02-15 04:40 UTC, mribeirodantas commented on docs/hello_nextflow/01_hello_world.md
> +Here we show you how to use the `publishDir` directive to TODO, the `resume` feature for when you need to re-launch the same workflow, and how to delete older work directories with `nextflow clean`.
```suggestion
Here we show you how to use the `publishDir` directive to store in an output folder all the main results from your pipeline run, the `resume` feature for when you need to re-launch the same workflow, and how to delete older work directories with `nextflow clean`.
```

2025-02-15 04:46 UTC, mribeirodantas commented on docs/hello_nextflow/01_hello_world.md
> +This directive tells Nextflow to copy the output(s) of the process to a designated output directory.
```suggestion
This directive tells Nextflow to publish the output(s) of the process to a designated output directory. By default, the outputs are published as symbolic links from the `work` directory.
```

2025-02-15 04:47 UTC, mribeirodantas commented on docs/hello_nextflow/01_hello_world.md
> +This is how we move results files outside of the working directories conveniently.
```suggestion
This is how we publish results files outside of the working directories conveniently.
```

2025-02-15 04:48 UTC, mribeirodantas commented on docs/hello_nextflow/01_hello_world.md
> +It is also possible to set the `publishDir` directive to make a symbolic link to the file instead of actually copying it.
```suggestion
```

2025-02-15 04:50 UTC, mribeirodantas commented on docs/hello_nextflow/01_hello_world.md
> +This is preferable when you're dealing with very large files you don't need to retain longer term.
```suggestion
When you're dealing with very large files that you don't need to retain for long, you may prefer to set the `publishDir` directive to make a symbolic link to the file instead of copying it.
```

2025-02-15 04:51 UTC, mribeirodantas commented on docs/hello_nextflow/01_hello_world.md
> +However, if you delete the work directory as part of a cleanup operation, you will lost access to the file, so always make sure you have actual copies of everything you care about before deleting any
```suggestion
However, if you delete the work directory as part of a cleanup operation, you will lose access to the file, so always make sure you have actual copies of everything you care about before deleting anything.
```

2025-02-15 04:53 UTC, mribeirodantas commented on docs/hello_nextflow/01_hello_world.md
> +    A newer syntax option had been proposed to make it possible to declare and publish workflow-level outputs, documented [here](https://www.nextflow.io/docs/latest/workflow.html#publishing-outputs).
```suggestion
    A newer syntax option documented [here](https://www.nextflow.io/docs/latest/workflow.html#publishing-outputs) has been proposed to make it possible to declare and publish workflow-level outputs.
```

2025-02-15 04:56 UTC, mribeirodantas commented on docs/hello_nextflow/01_hello_world.md
> +Look for the `cached:` bit that has been added in the process status line (line 6), which means that Nextflow has recognized that it has already done this work and simply re-used the result from the
```suggestion
Look for the `cached:` bit that has been added in the process status line (line 5), which means that Nextflow has recognized that it has already done this work and simply re-used the result from the previous successful run.
```

2025-02-15 04:57 UTC, mribeirodantas commented on docs/hello_nextflow/01_hello_world.md
> +Nextflow includes a convenient `-clean` command that can automatically delete the work subdirectories for past runs that you no longer care about, with several [options](https://www.nextflow.io/docs/
```suggestion
Nextflow includes a convenient `clean` subcommand that can automatically delete the work subdirectories for past runs that you no longer care about, with several [options](https://www.nextflow.io/docs/latest/reference/cli.html#clean) to control what will be deleted.
```

2025-02-15 05:03 UTC, mribeirodantas commented on docs/hello_nextflow/01_hello_world.md
> +```console title="output.txt" linenums="1"
```suggestion
```console title="results/output.txt" linenums="1"
```

2025-02-15 05:08 UTC, mribeirodantas commented on docs/hello_nextflow/01_hello_world.md
> +```console title="output.txt" linenums="1"
```suggestion
```console title="results/output.txt" linenums="1"
```

2025-02-15 05:11 UTC, mribeirodantas commented on docs/hello_nextflow/01_hello_world.md
> +```console title="output.txt" linenums="1"
```suggestion
```console title="results/output.txt" linenums="1"
```

2025-02-15 05:11 UTC, mribeirodantas requested changes
For now, it's a review only of Part I of the Hello Nextflow. ASAP I will review the other parts.

2025-02-18 03:10 UTC, mribeirodantas commented on docs/hello_nextflow/02_hello_channels.md
> +```console title="output.txt" linenums="1"
```suggestion
```console title="results/output.txt" linenums="1"
```

2025-02-18 03:14 UTC, mribeirodantas commented on docs/hello_nextflow/02_hello_channels.md
> +Functionally this will be exactly equivalent to how we had it set up before, but explicit instead of implicit.
`Channel.value(` would be functionally/exactly equivalent to how we had it set up before, but explicit instead of implicit. The implicit conversion to channel creates a value channel. `Channel.of`, which we're using now, creates a queue channel.

I'd rephrase this phrase as something like "Instead of having Nextflow create a channel implicitly, we are doing this explicitly now."

2025-02-18 03:16 UTC, mribeirodantas commented on docs/hello_nextflow/02_hello_channels.md
> +This creates a channel called `greeting_ch` using the `Channel.of()` channel factory, which sets up a simple value channel, and loads the string `'Hello Channels!'` to use as the greeting value.
```suggestion
This creates a channel called `greeting_ch` using the `Channel.of()` channel factory, which sets up a simple queue channel, and loads the string `'Hello Channels!'` to use as the greeting value.
```

If you want a value channel with `Channel.of`, you must apply a channel operator that returns a single channel element, such as `last,` `first,` `collect,` etc, e.g `Channel.of('Hello').first()`.

2025-02-18 03:19 UTC, mribeirodantas commented on docs/hello_nextflow/02_hello_channels.md
> +```console title="output.txt" linenums="1"
```suggestion
```console title="results/output.txt" linenums="1"
```

2025-02-18 03:22 UTC, mribeirodantas commented on docs/hello_nextflow/02_hello_channels.md
> +We just have to load more values into the channel.
I have always referred to the individual entries in a channel as elements, so as to not make people confused with what we mean by values when we talk about value channels (singletons). As we mention value channels in this part II, I'd rather call these elements. See the example below.

```
Channel.of('A', 'B', '[C, D]')
```
A, B, and [C, D] are three elements in the channel. C and D are items in the third channel.

2025-02-18 03:41 UTC, mribeirodantas commented on docs/hello_nextflow/02_hello_channels.md
> +You see that we get a single `Before flatten:` statement because at that point the channel contains one item, the original array.
So far, I have seen the words value, element, and item referring to the same thing (what is known as a channel element) in part II. I'd rather stick to elements (and items being the individual entries within an element).

2025-02-18 03:42 UTC, mribeirodantas commented on docs/hello_nextflow/02_hello_channels.md
> +You know how to use an operator like `flatten()` to transform the contents of a channel, and how to use the `view()` directive to inspect channel contents before and after applying an operator.
```suggestion
You know how to use an operator like `flatten()` to transform the contents of a channel, and how to use the `view()` operator to inspect channel contents before and after applying an operator.
```

2025-02-18 03:44 UTC, mribeirodantas commented on docs/hello_nextflow/02_hello_channels.md
> +Since we now want to use a file instead of simple values as the input, we can't use the `Channel.of()` channel factory from before.
```suggestion
Since we now want to use a file instead of simple strings as the input, we can't use the `Channel.of()` channel factory from before.
```

2025-02-18 03:49 UTC, mribeirodantas commented on docs/hello_nextflow/02_hello_channels.md
> +This means 'for each item in the channel, take the first of any elements it contains'.
```suggestion
This means 'for each element in the channel, take the first of any items it contains'.
```

2025-02-18 03:51 UTC, mribeirodantas commented on docs/hello_nextflow/02_hello_channels.md
> +- Three separate `After map:` statements: one for each greeting, which are now individual items in the channel.
```suggestion
- Three separate `After map:` statements: one for each greeting, which are now individual elements in the channel.
```

2025-02-18 03:53 UTC, mribeirodantas commented on docs/hello_nextflow/02_hello_channels.md
> +Remember the `params.greeting` parameter we set up in Part1?
Sometimes you add a space after Part. Some other times you don't. I'm for consistency + space after Part.
```suggestion
Remember the `params.greeting` parameter we set up in Part 1?
```

2025-02-18 03:54 UTC, mribeirodantas requested changes
Part 2 is very nice! I requested some minor changes. Tomorrow I will review the next parts.

2025-02-18 15:56 UTC, vdauwera commented on docs/hello_nextflow/02_hello_channels.md
> +You see that we get a single `Before flatten:` statement because at that point the channel contains one item, the original array.
Ok I agree with the push for consistency. But it's okay if some instances are left for later; getting the reorg merged soon is more important than having every word be perfect.

2025-02-18 15:58 UTC, vdauwera commented on docs/hello_nextflow/02_hello_channels.md
> +We just have to load more values into the channel.
ok feel free to suggest changes directly; otherwise let's do this in a refinement pass after this is merged in.

2025-02-18 16:17 UTC, vdauwera commented on docs/hello_nextflow/02_hello_channels.md
> +Functionally this will be exactly equivalent to how we had it set up before, but explicit instead of implicit.
fair point, addressed in commit

2025-02-18 16:37 UTC, mribeirodantas approved these changes

2025-02-18 17:20 UTC, maxulysse commented
I have just minor comments (but not related to the content itself, as I believe it's just comments related to the content that was ported)

- Why mixing multi lines comments (with the `/*...*/` and single line comments `//`?
  - Nowadays when I comment I use the shortcut from VS code and even multilines are using single comments, much less confusing I believe
- Why not using the tag directive for the processes when we use the flatten operator, so that we see a bit more than (1) (2) or (3)
- Why not using a params.yml over a params.json as json are really not meant to be edited by human hands

2025-02-18 17:49 UTC, merged